### ISSUE TITLE
Peer-to-peer review - module2-week2

### ISSUE THREAD

**Issue by gtekle** [clintonjosephs/awesome-books-es6#2]
Well done on the excellent job you have done! :clap: :clap: 
 - the way used classes :heavy_check_mark: 
 - good ES6 syntax usage :heavy_check_mark: 
 - good usage of external module (luxon) :heavy_check_mark: 
 - Well organized code :heavy_check_mark: 

However, we think these changes can further improve your code.

[Optional] It be good to use HTML5 validation to give feedback to the user on empty book registration.
[Optional] The list menu item should be active upon page load.

**Comment by clintonjosephs** [comment]
Thank you so much for point this out, it has been resolved as suggested.
